db:
  image: mysql
  volumes:
    - db_data:/var/lib/mysql
  restart: always
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: 123456
    MYSQL_DATABASE: ssm
    MYSQL_USER: lujin
    MYSQL_PASSWORD: 123456

redis:
  image: redis
  ports:
    - "6379:6379"
